#!/bin/bash
#SBATCH -p normal256
#SBATCH -n 32
#SBATCH -c 4
#SBATCH -N 1
#SBATCH -t 01:20:00
#SBATCH --job-name="w-e001-ar"
#SBATCH --mem=247000
#SBATCH --exclusiv
#SBATCH --export=NONE

# -N : nombre de noeuds
# -n : nombre TOTAL de taches MPI
# -c : nombre de threads (OMP)

# Start by cd to the TMPDIR because Slurm won't do it for you !!!!!!!
cd $TMPDIR

# change the output file name
mv ${SLURM_SUBMIT_DIR}/slurm-${SLURM_JOB_ID}.out ${SLURM_SUBMIT_DIR}/${SLURM_JOB_NAME}.o${SLURM_JOB_ID}
# ------------------------------------------------------------------------------------------------------------------------------------------------------
#                                                             ENVIRONMENT AND JOB SETTINGS
# ------------------------------------------------------------------------------------------------------------------------------------------------------

# Job management:
# ---------------
#JOB_INITDIR=$SLURM_CHECKPOINT_IMAGE_DIR
# Sorry, but JOB_NAME is lost with the mandatory --export=NONE
#export JOB_NAME=SDSCPL
#export JOB_ID=$SLURM_JOB_ID



#echo JOB_INITDIR=$JOB_INITDIR
#echo JOB_NAME=$JOB_NAME
#echo JOB_ID=$JOB_ID
export AUTO_PROFILE_HT="on"
# Number of nodes/mpi-tasks/omp-threads:
# -------------------------------------
# -------------------------------------
NNODES=$SLURM_JOB_NUM_NODES
# Number of MPI tasks per node:
MPITASKS_PER_NODE=$((SLURM_NTASKS/SLURM_JOB_NUM_NODES))
# Number of OPEN-MP threads per MPI task :
export OMP_NUM_THREADS=$((SLURM_CPUS_ON_NODE/MPITASKS_PER_NODE))
# Total number of MPI tasks:
MPI_TASKS=$SLURM_NTASKS
NPROC=$MPI_TASKS

echo NNODES=$NNODES
echo MPITASKS_PER_NODE=$MPITASKS_PER_NODE
echo MPI_TASKS=$MPI_TASKS
echo OMP_NUM_THREADS=$OMP_NUM_THREADS

# Specific environment variables :
# ------------------------------
set -x
export OMP_STACKSIZE=4G
export KMP_STACKSIZE=4G
export KMP_MONITOR_STACKSIZE=4G
set +x
ulimit -s unlimited

# Software default environment variables :
# --------------------------------------
set -x
export DR_HOOK=1
export DR_HOOK_IGNORE_SIGNALS=-1
export DR_HOOK_SILENT=1
export DR_HOOK_SHOW_PROCESS_OPTIONS=0
export MPL_MBX_SIZE=2048000000
export EC_PROFILE_HEAP=0
export EC_PROFILE_MEM=0
export EC_MPI_ATEXIT=0
export EC_MEMINFO=0
export OPENBLAS_NUM_THREADS=1
export MKL_CBWR="AUTO,STRICT"
export MKL_NUM_THREADS=1
export MKL_DEBUG_CPU_TYPE=5
export ECCODES_SAMPLES_PATH=/opt/softs/libraries/ICC_2018.5.274/eccodes-2.17.0/share/eccodes/ifs_samples/grib1
export ECCODES_DEFINITION_PATH=/opt/softs/libraries/ICC_2018.5.274/eccodes-2.17.0/share/eccodes/definitions
set +x
##--------------------------------------
###-----------JOB DIR-------------------
# ------------------------------------------------------------------------------------------------------------------------------------------------------
#                                                             EXPERIMENT SPECIFIC SETTINGS
# ------------------------------------------------------------------------------------------------------------------------------------------------------
jour=$(date '+%Y%m%d%H')

echo $jour
#AA=$(echo $jour | cut -c1-4)
AA=2022
#MM=$(echo $jour | cut -c5-6)
MM=12
#JJ=$(echo $jour | cut -c7-8)
JJ=26
HH=$(echo $jour | cut -c9-10)
YYYY=$AA
MMDD=$MM$JJ

#      *****************
#      *  Directories  *
#      *****************
#==================================================
echo "config file : "  $CONFIG_FILE

source /home/gmap/mrpe/chikhiw/config/./config_arome_500m


echo $AA$MM$JJ
#================== CREATE DIRECTORIES AND COOPY NEEDED FILES ========

#mkdir -p $OUT_CPL
#cd $TMPDIR

ln -s  $TMPDIR  $current_dir/tmp/tmp_e927

sed "s/NBPROC/$NPROC/g" $namel_e927 > fort.4
ln -s $EXECUTABLE MASTERODB

#====== options d'optimisation a l'execution ========
export ZOPT=""
CYCLE=46
NCONF=001
VERSION=meteo
CNMEXP='FPOS'
NSTOP=t0
TSTEP=1800.
ADVEC=eul
MODEL=arpifs
DOM='ALGE'
LMPOFF='FALSE'
LECHKEVO='FALSE'
pref='ALGE'
export CFPDOM=ALGE


#### START COUPLING ===============

for (( j=$start_ech; j<=$end_ech; j+=$step_ech ));
do
 i=$(printf "%04d" $j)
# COPY ICMSH 
cp $INP_DATA/${INP_DATA_name}_${i}  ICMSH${CNMEXP}INIT 

## COPY CLIMS 
cp  $clim_model_bigger                       Const.Clim
cp  $clim_model_config                       const.clim.ALGE 
# exécution

$execution_bin  -genv I_MPI_DEBUG=1000 ./MASTERODB    > lola 1>&2

mv  PFFPOSALGE+0000 $OUT_CPL/COUPLAGE_AROME_${i}
done

#      ***************
#      *  Listing    *
#      ***************
if [ -a NODE.001_01 ] ; then
  for file in NODE* ; do
    \cat $file
  done
fi
