#!/bin/bash
#SBATCH --partition=Researches
#SBATCH --job-name="ALA-E001"
#SBATCH -n 64
#SBATCH -c 1
#SBATCH -N 4
#SBATCH -t 23:00:00
#SBATCH --exclusive
#SBATCH --verbose
#SBATCH --output=stdout_e001
#SBATCH --error=stderr_e001
# -N : nombre de noeuds
# -n : nombre TOTAL de taches MPI
# -c : nombre de threads (OMP)
echo "@@ `date`"
start=`date +%T`
# echo $(date +"%T") > ${HOME}/onm/RUN/LOGS/arome_execu_time

. ~/.bash_profile
MPI_TASKS=$SLURM_NTASKS   
NPROC=$MPI_TASKS
echo $NPROC
MPITASKS_PER_NODE=$((SLURM_NTASKS/SLURM_JOB_NUM_NODES))
export OMP_NUM_THREADS=$((SLURM_CPUS_ON_NODE/MPITASKS_PER_NODE))
# ========================================= DZ
export EC_PROFILE_HEAP=0

#=======BEGIN FABRIC============= 
#export I_MPI_DEBUG=100
#=======END FABRIC===============

export F_PROGINF=DETAIL
export F_FTRACE=FMT2
export F_RECLUNIT=BYTE
export F_SYSLEN=1024
export F_FMTBUF=131072
export F_SETBUF=32768
export F_SETBUF6=0
export F_SETBUF0=0
export F_ERRCNT=1
export DR_HOOK=0
export DR_HOOK_IGNORE_SIGNALS=-1
export MPIPROGINF="ON"
export MPIDEBUG="ON"
export MPISUSPEND="ON"

export MPIEXPORT="EC_PROFILE_HEAP,F_PROGINF,F_FTRACE,F_RECLUNIT,F_SYSLEN,F_FMTBUF,F_SETBUF,F_SETBUF6,F_SETBUF0,F_ERRCNT,DR_HOOK,DR_HOOK_IGNORE_SIGNALS,MPIPROG
INF,MPIDEBUG,MPISUSPEND"

#==========================================

NNODES=$SLURM_JOB_NUM_NODES   #Ana
echo NNODES=$NNODES
echo MPITASKS_PER_NODE=$MPITASKS_PER_NODE
echo MPI_TASKS=$MPI_TASKS
echo OMP_NUM_THREADS=$OMP_NUM_THREADS
export KMP_STACKSIZE=1G
export KMP_MONITOR_STACKSIZE=1G
ulimit -s unlimited
export DR_HOOK_SILENT=1
export DR_HOOK_OPT=prof
export MPL_MBX_SIZE=2048000000
export EC_MPI_ATEXIT=0
export ECCODES_SAMPLES_PATH=/onm/dem/home/wchikhi/LIB/eccodes/share/eccodes/ifs_samples/grib1
export ECCODES_DEFINITION_PATH=/onm/dem/home/wchikhi/LIB/eccodes/share/eccodes/definitions



#=================== ENVIRONMENT ==================
#source /opt/ohpc/pub/intel/oneapi/setvars.sh
export FI_PROVIDER=verbs
export FI_VERBS_DEVICE_NAME=mlx4_0
export FI_VERBS_IFACE=ib0
#==================================================
source $CONFIG_FILE
echo $CONFIG_FILE


rr=00
AA=`echo $DATE |cut -c1-4`
MM=`echo $DATE |cut -c5-6`
DD=`echo $DATE |cut -c7-8`

mkdir -p $tmpdir_e001
cd $tmpdir_e001

ln -sf  $tmpdir_e001  $current_dir/tmp_e001
# options d'optimisation a l'execution.
export ZOPT=""
date
CYCLE=43
NCONF=001
VERSION=meteo
CNMEXP='AL03'
NSTOP=h048
TSTEP=60.
ADVEC=sli
MODEL=aladin
DOM='ALGE01'
LMPOFF='FALSE'
LECHKEVO='FALSE'
pref='ALGE01'


# fichiers coupleurs
DIR_DATA=${HOME}/exp/V8.0

ln -s ${ecoclimap_dir}/ecoclimapI_covers_param.bin       ecoclimapI_covers_param.bin
ln -s ${ecoclimap_dir}/ecoclimapII_eu_covers_param.bin   ecoclimapII_eu_covers_param.bin
ln -s ${ecoclimap_dir}/ecoclimapII_af_covers_param.bin  ecoclimapII_af_covers_param.bin
sed "s/NBPROC/$NPROC/g" $namel_e001 > fort.4
cp $namel_e001_sfx    EXSEG1.nam
ln -sf $EXECUTABLE  MASTERODB 
cp   $const/*  .

for (( j=$start_ech; j<=$end_ech; j+=$step_ech ));
do
 ECHPL=$(printf "%03d" $j)
 set -x
  # fichiers coupleurs 
ln -sf $OUT_CPL/COUPLAGE_AROME_${AA}${MM}${DD}00_0${ECHPL}  ELSCF${CNMEXP}ALBC${ECHPL} 

done

cp ELSCF${CNMEXP}ALBC000 ICMSH${CNMEXP}INIT

ln -sf $OUT_CPL/INIT_SURF_${AA}${MM}${DD}00 ICMSH${CNMEXP}INIT.sfx

export CFPDOM=ALGE01

ln -sf $clim_pgd             Const.Clim.sfx 
ln -sf $clim_model_config    Const.Clim 
ln -sf $clim_bdap_config     const.clim.${CFPDOM}


#================ EXCECUTION ===================================


$execution_bin   -genv I_MPI_DEBUG=1000 ./MASTERODB    > lola 1>&2


#==============================================================

#      ***************
#      *  Listing    *
#      ***************
if [ -a NODE.001_01 ] ; then
  for file in NODE* ; do
    \cat $file
  done
fi

mkdir -p $OUT_ICMSH $OUT_FPOS

for (( j=$start_ech; j<=$end_ech; j+=$step_ech ));;
do
 i=$(printf "%02d" $j)
mv ICMSHAL03+00${i} $OUT_ICMSH
mv PFAL03ALGE01+00${i} $OUT_FPOS

done
