#!/bin/bash
#SBATCH --partition=Researches
#SBATCH --job-name="ALA-E001"
#SBATCH -n 64
#SBATCH -c 1
#SBATCH -N 4
#SBATCH -t 23:00:00
#SBATCH --exclusive
#SBATCH --verbose
#SBATCH --output=stdout
#SBATCH --error=stderr
# -N : nombre de noeuds
# -n : nombre TOTAL de taches MPI
# -c : nombre de threads (OMP)
echo "@@ `date`"
start=`date +%T`
# echo $(date +"%T") > ${HOME}/onm/RUN/LOGS/arome_execu_time

. ~/.bash_profile
MPI_TASKS=$SLURM_NTASKS   
NPROC=$MPI_TASKS
echo $NPROC
MPITASKS_PER_NODE=$((SLURM_NTASKS/SLURM_JOB_NUM_NODES))
export OMP_NUM_THREADS=$((SLURM_CPUS_ON_NODE/MPITASKS_PER_NODE))
# ========================================= DZ
export EC_PROFILE_HEAP=0

#=======BEGIN FABRIC============= 
#export I_MPI_DEBUG=100
#=======END FABRIC===============

export F_PROGINF=DETAIL
export F_FTRACE=FMT2
export F_RECLUNIT=BYTE
export F_SYSLEN=1024
export F_FMTBUF=131072
export F_SETBUF=32768
export F_SETBUF6=0
export F_SETBUF0=0
export F_ERRCNT=1
export DR_HOOK=0
export DR_HOOK_IGNORE_SIGNALS=-1
export MPIPROGINF="ON"
export MPIDEBUG="ON"
export MPISUSPEND="ON"

export MPIEXPORT="EC_PROFILE_HEAP,F_PROGINF,F_FTRACE,F_RECLUNIT,F_SYSLEN,F_FMTBUF,F_SETBUF,F_SETBUF6,F_SETBUF0,F_ERRCNT,DR_HOOK,DR_HOOK_IGNORE_SIGNALS,MPIPROG
INF,MPIDEBUG,MPISUSPEND"

#==========================================

NNODES=$SLURM_JOB_NUM_NODES   #Ana
echo NNODES=$NNODES
echo MPITASKS_PER_NODE=$MPITASKS_PER_NODE
echo MPI_TASKS=$MPI_TASKS
echo OMP_NUM_THREADS=$OMP_NUM_THREADS
export KMP_STACKSIZE=1G
export KMP_MONITOR_STACKSIZE=1G
ulimit -s unlimited
export DR_HOOK_SILENT=1
export DR_HOOK_OPT=prof
export MPL_MBX_SIZE=2048000000
export EC_MPI_ATEXIT=0
export ECCODES_SAMPLES_PATH=/onm/dem/home/wchikhi/LIB/eccodes/share/eccodes/ifs_samples/grib1
export ECCODES_DEFINITION_PATH=/onm/dem/home/wchikhi/LIB/eccodes/share/eccodes/definitions
#export LD_LIBRARY_PATH=/shared/tools/12.20/lib:/shared/tools/12.20/lib64:/opt/ohpc/pub/compiler/gcc/9.3.0/lib64



#=================== ENVIRONMENT ==================

#source /onm/dit/home/ibelabbaci/oneapi.sh
#source /shared/composer_xe_2019.update4
#source /onm/dit/home/ibelabbaci/intel/oneapi/setvars.sh
source /opt/ohpc/pub/intel/oneapi/setvars.sh

export FI_PROVIDER=verbs
#export FI_PROVIDER=tcp
#export FI_PROVIDER=verbs
#export I_MPI_FALLBACK=0
#export I_MPI_HYDRA_DEBUG=on
#export FI_LOG_LEVEL=debug
#export FI_LOG_PROV=
#export FI_LOG_SUBSYS=

export FI_VERBS_DEVICE_NAME=mlx4_0
export FI_VERBS_IFACE=ib0


#==================================================


#MM=$(date +"%m")
#MM=01
#DD=01
#AA=2022
rr=00
DATE=`cat /onm/dem/home/wchikhi/majoper/arome/date`
AA=`echo $DATE |cut -c1-4`
MM=`echo $DATE |cut -c5-6`
DD=`echo $DATE |cut -c7-8`
#echo "Journée du : "$MM-$JJ-$AA" JobID Forecast : " ${SLURM_JOB_ID} >> $HOME/onm/dem/home/wchikhi/exp/AROME/jobs.txt
echo $AA$MM$JJ
echo "START CONFIG-E001 de  la journée du : ${AA}${MM}${DD} de  AROME CY46 2.5 - 90 NIV À : "  $(date +"%T") >> ${HOME}/majoper/arome/benchmark/execu_time

#tmpdir="${HOME}/tmp/AROME/ARO-E001-$(date +"%H%M%S")"
tmpdir="${HOME}/tmp/AROME/AROM-E001-${DD}${MM}${AA}"
mkdir -p $tmpdir
cd $tmpdir
rm -f *

rm -rf /onm/dem/home/wchikhi/majoper/arome/e001/tmp 

ln -sf  $tmpdir  /onm/dem/home/wchikhi/majoper/arome/e001/tmp
# options d'optimisation a l'execution.
export ZOPT=""
date
CYCLE=43
NCONF=001
VERSION=meteo
CNMEXP='AL03'
NSTOP=h048
TSTEP=60.
ADVEC=sli
MODEL=aladin
DOM='ALGE01'
LMPOFF='FALSE'
LECHKEVO='FALSE'
pref='ALGE01'


# fichiers coupleurs
        ############################################## < LOG > ################################################
        echo "   Préparation des fichiers coupleurs" >> ${HOME}/onm/RUN/LOGS/journal-chaine-du-$(date +"%d-%m-%Y")
        echo "   " >>${HOME}/onm/RUN/LOGS/journal-chaine-du-$(date +"%d-%m-%Y")
        ############################################## < LOG > ################################################
DIR_DATA=${HOME}/exp/V8.0

ln -s ${DIR_DATA}/ecoclimapI_covers_param.bin       ecoclimapI_covers_param.bin
ln -s ${DIR_DATA}/ecoclimapII_eu_covers_param.bin   ecoclimapII_eu_covers_param.bin
ln -s ${DIR_DATA}/ecoclimapII_af_covers_param.bin  ecoclimapII_af_covers_param.bin
sed "s/NBPROC/$NPROC/g" /onm/dem/home/wchikhi/majoper/arome/e001/namel_e001_cy46 > fort.4
cp /onm/dem/home/wchikhi/exp/AROME/e001/namel_previ_surf    EXSEG1.nam
#ln -sf /onm/dem/home/wchikhi/pack/46t1_bf03.01.INTEL.x/bin/MASTERODB . 

ln -sf /onm/dem/home/wchikhi/pack/46t1_bf1.01.INTEL.x/bin/MASTERODB .
cp   /onm/dem/home/wchikhi/exp/CONST/*  .

  ECHCPL="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"

set +x
echo ''
echo ' Acquisition de l ebauche  et des fichiers coupleurs '
echo ' Guess or analysis and coupling files '
echo ''
set -x
# fichiers coupleurs 
for iech in $ECHCPL
 do
    case $iech in
      00) icoupl='000' ;;
      01) icoupl='001' ;;
      02) icoupl='002' ;;
      03) icoupl='003' ;;
      04) icoupl='004' ;;
      05) icoupl='005' ;;
      06) icoupl='006' ;;
      07) icoupl='007' ;;
      08) icoupl='008' ;;
      09) icoupl='009' ;;
      10) icoupl='010' ;;
      11) icoupl='011' ;;
      12) icoupl='012' ;;
      13) icoupl='013' ;;
      14) icoupl='014' ;;
      15) icoupl='015' ;;
      16) icoupl='016' ;;
      17) icoupl='017' ;;
      18) icoupl='018' ;;
      19) icoupl='019' ;;
      20) icoupl='020' ;;
      21) icoupl='021' ;;
      22) icoupl='022' ;;
      23) icoupl='023' ;;
      24) icoupl='024' ;;
      25) icoupl='025' ;;
      26) icoupl='026' ;;
      27) icoupl='027' ;;
      28) icoupl='028' ;;
      29) icoupl='029' ;;
      30) icoupl='030' ;;
      31) icoupl='031' ;;
      32) icoupl='032' ;;
      33) icoupl='033' ;;
      34) icoupl='034' ;;
      35) icoupl='035' ;;
      36) icoupl='036' ;;
      37) icoupl='037' ;;
      38) icoupl='038' ;;
      39) icoupl='039' ;;
      40) icoupl='040' ;;
      41) icoupl='041' ;;
      42) icoupl='042' ;;
      43) icoupl='043' ;;
      44) icoupl='044' ;;
      45) icoupl='045' ;;
      46) icoupl='046' ;;
      47) icoupl='047' ;;
      48) icoupl='048' ;;
    esac 


ln -sf  /onm/dem/home/wchikhi/output/majoper/AROME/CPL/${DD}${MM}${AA}/COUPLAGE_AROME_00${iech} ELSCF${CNMEXP}ALBC${icoupl}
#ln -sf /fennecData/data/chprod/AROME/COUPLAGE/${AA}/${MM}/${DD}/r00/COUPLAGE_AROME_${AA}${MM}${DD}00_00${iech} ELSCF${CNMEXP}ALBC${icoupl} 
done

cp ELSCF${CNMEXP}ALBC000 ICMSH${CNMEXP}INIT

cp /onm/dem/home/wchikhi/output/majoper/AROME/CPL/${DD}${MM}${AA}/INIT_SURF.fa ICMSH${CNMEXP}INIT.sfx
#cp  /fennecData/data/chprod/AROME/COUPLAGE/${AA}/${MM}/${DD}/r00/INIT_SURF_${AA}${MM}${DD}00 ICMSH${CNMEXP}INIT.sfx 
#ln -sf ELSCF${CNMEXP}ALBC000 ICMSHALADINIT

export CFPDOM=ALGE01

ln -sf  /onm/dem/home/wchikhi/majoper/clim/arome/bdap/AROME_bdap_m${MM} const.clim.${CFPDOM}
#ln -sf  /onm/dem/home/wchikhi/exp/arome/Const.Clim.${MM} Const.Clim
ln -sf /onm/dem/home/wchikhi/majoper/clim/arome/AROME_model_m${MM} Const.Clim
ln -sf /onm/dem/home/wchikhi/majoper/clim/arome/PGD.fa  Const.Clim.sfx


#================ EXCECUTION ===================================

#/opt/intel/compilers_and_libraries_2019.4.243/linux/mpi/intel64/bin/mpirun   -env I_MPI_DEBUG 100 ./MASTERODB    > lola 2>&1 

/opt/ohpc/pub/intel/oneapi/mpi/latest/bin/mpirun   -genv I_MPI_DEBUG=1000 ./MASTERODB    > lola 1>&2


#==============================================================

#      ***************
#      *  Listing    *
#      ***************
if [ -a NODE.001_01 ] ; then
  for file in NODE* ; do
    \cat $file
        ############################################# < LOG > #################################################
        echo "   Listing "$file >>${HOME}/onm/RUN/LOGS/journal-chaine-du-$(date +"%d-%m-%Y")
        ############################################# < LOG > #################################################
  done
fi
        echo "   " >>${HOME}/onm/RUN/LOGS/journal-chaine-du-$(date +"%d-%m-%Y")
        echo "   Génération des ICMSH" >>${HOME}/onm/RUN/LOGS/journal-chaine-du-$(date +"%d-%m-%Y")
        ############################################# < LOG > #################################################

mkdir -p ${HOME}/output/majoper/AROME/FPOS/${DD}${MM}${AA}
mkdir -p ${HOME}/output/majoper/AROME/ICMSH/${DD}${MM}${AA}


for i in {00..48..01}
do
mv ICMSHAL03+00${i} ${HOME}/output/majoper/AROME/ICMSH/${DD}${MM}${AA}/.
done

for i in {00..48..01}        #00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48
do
mv PFAL03ALGE01+00${i} ${HOME}/output/majoper/AROME/FPOS/${DD}${MM}${AA}/.
done

ls -lrt



echo " Time d'éxecution du job e001 est de `time` secondes " >> ~/majoper/benchmark

echo "END CONFIG-E001 de  la journée du : ${AA}${MM}${DD} de  AROME CY46 2.5 - 90 NIV À : "  $(date +"%T") >> ${HOME}/majoper/arome/benchmark/execu_time

### changement de Date Auto 
exit 


echo $date
DD=`expr $DD + 1`



if [ $DD -lt 10 ]
then
DD="0"$DD
else
DD=$DD
fi
     
if [ $DD -gt 31 ] 
then 
exit
else 
DATE1=$AA$MM$DD
echo $DATE1
echo $DATE1 > /onm/dem/home/wchikhi/exp/AROME/e001/date
cd   /onm/dem/home/wchikhi/exp/AROME/e001
sleep 5 
sbatch job 
fi 
exit 
